// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TawseeltekAPI.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026145044_AddUserDevicePK")]
    partial class AddUserDevicePK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TawseeltekAPI.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LicenseImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleLicenseImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("DriverID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.DriverBalanceLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("DriverID");

                    b.ToTable("DriverBalanceLogs");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<bool>("IsSupportMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PassengerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Penalty", b =>
                {
                    b.Property<int>("PenaltyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenaltyID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PenaltyID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("DriverID");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Price", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<int>("FromCityID")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToCityID")
                        .HasColumnType("int");

                    b.HasKey("PriceID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("ToCityID");

                    b.HasIndex("FromCityID", "ToCityID")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Ride", b =>
                {
                    b.Property<int>("RideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RideID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("FromCityID")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSeat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoutePolyline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatsTaken")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToCityID")
                        .HasColumnType("int");

                    b.HasKey("RideID");

                    b.HasIndex("DriverID");

                    b.HasIndex("FromCityID");

                    b.HasIndex("ToCityID");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.RidePassenger", b =>
                {
                    b.Property<int>("RidePassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RidePassengerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.Property<int>("RideID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RidePassengerID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("RideID");

                    b.HasIndex("UserID");

                    b.ToTable("RidePassengers");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.UserDevice", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DeviceID");

                    b.HasIndex("UserID");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Driver", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("TawseeltekAPI.Models.Driver", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.DriverBalanceLog", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "CreatedBy")
                        .WithMany("BalanceLogsCreated")
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TawseeltekAPI.Models.Driver", "Driver")
                        .WithMany("BalanceLogs")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Message", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Notification", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Passenger", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "User")
                        .WithOne("Passenger")
                        .HasForeignKey("TawseeltekAPI.Models.Passenger", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Penalty", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "CreatedBy")
                        .WithMany("PenaltiesCreated")
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TawseeltekAPI.Models.Driver", "Driver")
                        .WithMany("Penalties")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Price", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.City", "FromCity")
                        .WithMany("PricesFrom")
                        .HasForeignKey("FromCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.City", "ToCity")
                        .WithMany("PricesTo")
                        .HasForeignKey("ToCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Ride", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.Driver", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.City", "FromCity")
                        .WithMany("RidesFrom")
                        .HasForeignKey("FromCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.City", "ToCity")
                        .WithMany("RidesTo")
                        .HasForeignKey("ToCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.RidePassenger", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.Passenger", "Passenger")
                        .WithMany("RidePassengers")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.Ride", "Ride")
                        .WithMany("RidePassengers")
                        .HasForeignKey("RideID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TawseeltekAPI.Models.User", null)
                        .WithMany("RidePassengers")
                        .HasForeignKey("UserID");

                    b.Navigation("Passenger");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.UserDevice", b =>
                {
                    b.HasOne("TawseeltekAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TawseeltekAPI.Models.City", b =>
                {
                    b.Navigation("PricesFrom");

                    b.Navigation("PricesTo");

                    b.Navigation("RidesFrom");

                    b.Navigation("RidesTo");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Driver", b =>
                {
                    b.Navigation("BalanceLogs");

                    b.Navigation("Penalties");

                    b.Navigation("Rides");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Passenger", b =>
                {
                    b.Navigation("RidePassengers");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.Ride", b =>
                {
                    b.Navigation("RidePassengers");
                });

            modelBuilder.Entity("TawseeltekAPI.Models.User", b =>
                {
                    b.Navigation("BalanceLogsCreated");

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Passenger")
                        .IsRequired();

                    b.Navigation("PenaltiesCreated");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RidePassengers");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
